src/objects/Accounting_Category__c.object
<CustomObject>
    <fields>
        <fullName>Category_Code__c</fullName>
        <inlineHelpText>Used to determine what section a Code/Category appears in/applies to</inlineHelpText>
        <label>Category Code</label>
        <picklist>
            <picklistValues>
                <fullName>SALARY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRINGE BENEFIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OVERHEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPENSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVENUE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>99</defaultValue>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting Category</label>
    <nameField>
        <label>Accounting Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Code__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Category__c</fullName>
        <label>Accounting Category</label>
        <referenceTo>Accounting_Category__c</referenceTo>
        <relationshipLabel>Accounting Codes</relationshipLabel>
        <relationshipName>Accounting_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Include_on_Budget_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include on Budget Report</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Budget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Determine&apos;s who has access to Budget Data</description>
    <fields>
        <fullName>Id_Value__c</fullName>
        <label>Id Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <inlineHelpText>To store string values for use in Budget Reports</inlineHelpText>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Budget Settings</label>
</CustomObject>

src/objects/Deliverable__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Deliverables</relationshipLabel>
        <relationshipName>Deliverables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>ChildDepartments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Dept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Policy Department?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Department__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Roll Up Department</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Management__c.object
<CustomObject>
    <fields>
        <fullName>Grant_End_Date__c</fullName>
        <inlineHelpText>Official End Date of Grant</inlineHelpText>
        <label>Grant End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_End__c</fullName>
        <inlineHelpText>End date of grant period.</inlineHelpText>
        <label>Grant Period: End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_Start__c</fullName>
        <inlineHelpText>Start date of grant period.</inlineHelpText>
        <label>Grant Period: Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Provisions__c</fullName>
        <inlineHelpText>Any notes about the grant requirements other than reporting.</inlineHelpText>
        <label>Grant Provisions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grant_Start_Date__c</fullName>
        <inlineHelpText>Official Start Date of Grant</inlineHelpText>
        <label>Grant Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Grant Management</relationshipLabel>
        <relationshipName>Grant_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Grant Management</relationshipLabel>
        <relationshipName>Grant_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Management</label>
    <nameField>
        <label>Grant Management Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GrantManagementSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Grant Management App</description>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Id_Value__c</fullName>
        <label>Id Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Management Settings</label>
</CustomObject>

src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <label>Taxonomy</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Issue_Utility_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store Field Map for Issue Intersection Object VF Component</description>
    <fields>
        <fullName>Issue_Intersection_Field__c</fullName>
        <label>Issue Intersection Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <inlineHelpText>Store generic string parameters</inlineHelpText>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Issue Utility Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Grant_Period_End__c</fullName>
        <inlineHelpText>End date of grant period.</inlineHelpText>
        <label>Grant Period: End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_Start__c</fullName>
        <inlineHelpText>Start date of grant period.</inlineHelpText>
        <label>Grant Period: Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Provisions__c</fullName>
        <inlineHelpText>Any notes about the grant requirements other than reporting.</inlineHelpText>
        <label>Grant Provisions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Opty_Grant_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map fields from Opportunity to Grant on Conversion</description>
    <fields>
        <fullName>Grant_Field__c</fullName>
        <label>Grant Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Order__c</fullName>
        <defaultValue>999</defaultValue>
        <label>Page Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_on_Page__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Section on Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity to Grant Field Map</label>
</CustomObject>

src/objects/ParticipationControllerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store Field setting for Staff Participation Controller so you can add it to any related object</description>
    <fields>
        <fullName>Staff_Participation_Field__c</fullName>
        <inlineHelpText>What is the field on the Staff Participation Object for this object</inlineHelpText>
        <label>Staff Participation Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participation Controller Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <description>Put the Contact Id of this user&apos;s staff Contact record into this field.</description>
        <inlineHelpText>Put the Contact Id of this user&apos;s staff Contact record into this field.</inlineHelpText>
        <label>Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestDataFactory_TEST.cls
/*
    Copyright (c) 2013, Bridge Farm Consulting Inc
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Bridge Farm Consulting Inc nor 
      Center for American Progress nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Center for American Progress/Bridge Farm Consulting Inc
* @date 2014 (1.x)
* @description 
* create test data for all tests to centralize setup and maintenance
*/

@isTest
public with sharing class TestDataFactory_TEST {

public static Account setupNewAccount (Boolean bCreate, String sName) {
Account a = new Account (Name = sName);
if (bCreate) {
insert a;
}
return a;
}

public static Project__c setupNewProject (Boolean bCreate, String sName) {
Project__c p = new Project__c (Name = sName);
if (bCreate) {
insert p;
}
return p;
}


public static Deliverable__c setupNewDeliverable (Boolean bCreate, String sName, Id ProjectId) {
Deliverable__c d = new Deliverable__c (Name = sName, Project__c = ProjectId);
if (bCreate) {
insert d;
}
return d;
}

public static Grant_Management__c setupNewGrant (Boolean bCreate, String sName, Id OptyId) {
Grant_Management__c gm = new Grant_Management__c (Name = sName, Source_Opportunity__c = OptyId);
if (bCreate) {
insert gm;
}
return gm;
}

public static Opportunity setupNewOpty (Boolean bCreate, String sName, Date dtCloseDate, Id AccountId) {
Opportunity o = new Opportunity (Name = sName, CloseDate = dtCloseDate);
o.StageName = 'Closed Won';
if (bCreate) {
insert o;
}
return o;
}

public static void setupPCESettings(Boolean bClear) {

List<ParticipationControllerSettings__c> pcesettings;

if (bClear) {
     pcesettings = ParticipationControllerSettings__c.getall().values();
     delete pcesettings;
}

pcesettings = new List<ParticipationControllerSettings__c> ();  
pcesettings.add(new ParticipationControllerSettings__c (Name = 'Opportunity', Staff_Participation_Field__c = 'Opportunity__c'));
pcesettings.add(new ParticipationControllerSettings__c (Name = 'Grant_Management__c', Staff_Participation_Field__c = 'Grant_Management__c'));
insert pcesettings;
}

public static void setupOrgSettings(Boolean bClear, Id AccountId) {

List<GrantManagementSettings__c> gm;

if (bClear) {
     gm = GrantManagementSettings__c.getall().values();
     delete gm;
}

gm = new List<GrantManagementSettings__c>();
gm.add(new GrantManagementSettings__c(Name = 'OurAccountId', Id_Value__c = AccountId));
gm.add(new GrantManagementSettings__c(Name = 'ContactDepartment', String_Value__c = 'gm_Department_Reference__c'));
gm.add(new GrantManagementSettings__c(Name = 'ContactIdFieldonUser', String_Value__c = 'Contact_ID__c'));
gm.add(new GrantManagementSettings__c(Name = 'UserFieldonContact', String_Value__c = 'gm_Related_User_Record__c'));
gm.add(new GrantManagementSettings__c(Name = 'PostLeadStaffertoChatter', Boolean_Value__c = TRUE));


insert gm;
}


public static void setupOptytoGrantFieldSettings(Boolean bClear) {
List<Opty_Grant_Fields__c> ogf;

if (bClear) {
     ogf = Opty_Grant_Fields__c.getall().values();
     delete ogf;
}

ogf = new List<Opty_Grant_Fields__c>();
ogf.add (new Opty_Grant_Fields__c(Name = 'Id', Grant_Field__c = 'Source_Opportunity__c', Page_Order__c = 1, Section_on_Page__c = 1));
ogf.add (new Opty_Grant_Fields__c(Name = 'Name', Grant_Field__c = 'Name', Page_Order__c = 1, Section_on_Page__c = 1));
ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Period_Start__c', Grant_Field__c = 'Grant_Start_Date__c', Page_Order__c = 1, Section_on_Page__c = 1));
ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Period_End__c', Grant_Field__c = 'Grant_End_Date__c', Page_Order__c = 1, Section_on_Page__c = 1));

ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Provisions__c', Grant_Field__c = 'Grant_Provisions__c', Page_Order__c = 20, Section_on_Page__c = 2));


insert ogf;
}

public static void setupBudgetSettings(Boolean bClear, Id PermSet, String cCodes) {
List<Budget_Settings__c> bud;

if (bClear) {
     bud = Budget_Settings__c.getall().values();
     delete bud;
}

bud = new List<Budget_Settings__c>();
if (PermSet != null) {
bud.add (new Budget_Settings__c(Name = 'PermissionSet', Id_Value__c  = PermSet));
}
bud.add (new Budget_Settings__c(Name = 'CompanyCodes', String_Value__c  = cCodes));
bud.add (new Budget_Settings__c(Name = 'StartingBalanceCode', String_Value__c  = '3200'));


insert bud;
}


public static List<Department__c> setupDepartments() {

List<Department__c> dparents = new List<Department__c> ();
dparents.add(new Department__c (Name = 'Parent 1', Roll_Up_Department__c = TRUE, Code__c = 1, Policy_Dept__c = TRUE));
dparents.add(new Department__c (Name = 'Parent 2', Roll_Up_Department__c = FALSE, Code__c = 2));
insert dparents;

List<Department__c> childdepts = new List<Department__c> ();
childdepts.add(new Department__c (Name = 'Child 1', Parent_Department__c = dparents[0].Id, Code__c = 20));
childdepts.add(new Department__c (Name = 'Child 1a', Parent_Department__c = dparents[0].Id, Code__c = 72, Policy_Dept__c = TRUE));
childdepts.add(new Department__c (Name = 'Child 2', Parent_Department__c = dparents[1].Id, Code__c = 75, Policy_Dept__c = TRUE));
childdepts.add(new Department__c (Name = 'Child 2a', Parent_Department__c = dparents[1].Id, Code__c = 82));
childdepts.add(new Department__c (Name = 'Child 2b', Parent_Department__c = dparents[1].Id, Code__c = 84));
childdepts.add(new Department__c (Name = 'Child 2c', Parent_Department__c = dparents[1].Id, Code__c = 86));

insert childdepts;
return childdepts;
}

public static void setupIssueUtilitySettings(Boolean bClear) {
List<Issue_Utility_Settings__c> issuesettings;


if (bClear) {
     issuesettings = Issue_Utility_Settings__c.getall().values();
     delete issuesettings;
}

issuesettings = new List<Issue_Utility_Settings__c>();
issuesettings.add (new Issue_Utility_Settings__c(Name = 'Deliverable__c', Issue_Intersection_Field__c  = 'Deliverable__c'));
issuesettings.add (new Issue_Utility_Settings__c(Name = 'TaxonomyStrings', String_Value__c  = 'Issue;'));

insert issuesettings;
}


public static List<Issue__c> setupIssues() {

List<Issue__c> dparents = new List<Issue__c> ();
dparents.add(new Issue__c (Name = 'Parent Issue 1'));
dparents.add(new Issue__c (Name = 'Parent Issue 2'));
insert dparents;

List<Issue__c> childissues = new List<Issue__c> ();
childissues.add(new Issue__c (Name = 'Child 1', Parent_Issue__c = dparents[0].Id, Taxonomy__c = 'Issue'));
childissues.add(new Issue__c (Name = 'Child 1a', Parent_Issue__c = dparents[0].Id, Taxonomy__c = 'Issue'));
childissues.add(new Issue__c (Name = 'Child 2', Parent_Issue__c = dparents[1].Id, Taxonomy__c = 'Issue'));

insert childissues;
return childissues;
}

public static User CreateTestUser (String sUserName) {

 User u = new User(

          Username = sUserName,
          Alias = 'standt',
          email = 'standarduser@example.com',
          emailencodingkey = 'UTF-8',
          LastName = 'Testing',
          LanguageLocaleKey = 'en_US',
          LocaleSidKey = 'en_US',
          ProfileId = userinfo.getProfileId(),
          TimeZoneSidKey = 'America/Los_Angeles'

        );

insert u;

return u;


}

public static void setChatterFeed (Id RecordId) {

ConnectApi.FeedItemPage testPage = new ConnectApi.FeedItemPage();
        List<ConnectApi.FeedItem> testItemList = new List<ConnectApi.FeedItem>();
        testItemList.add(new ConnectApi.FeedItem());
        testItemList.add(new ConnectApi.FeedItem());
        testItemList.add(createFeedItemwithAttachment(RecordId));
        testPage.items = testItemList;
        
        // Set the test data
        ConnectApi.ChatterFeeds.setTestGetFeedItemsFromFeed(null, ConnectApi.FeedType.Record, RecordId, testPage);

}

public static ConnectApi.FeedItem createFeedItemwithAttachment (Id RecordId) {

String s = 'Test Attach One';
blob sBody = blob.valueof(s);

ConnectApi.BinaryInput newChatterFile = new ConnectApi.BinaryInput(sBody, 'txt', 'Test A 1');
ConnectApi.NewFileAttachmentInput cai = new ConnectApi.NewFileAttachmentInput ();
cai.description = 'Test File 1';
cai.title = 'Test A 1';

    ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
    input.attachment = cai;
    input.visibility = ConnectApi.FeedItemVisibilityType.InternalUsers; 
        //TargetRecordId is the record id of the chatter feed you want to post on
    ConnectApi.FeedItem fi = ConnectApi.ChatterFeeds.postFeedItem(null, 
                                        ConnectApi.FeedType.Record,
                                        RecordId, 
                                        input,
                                        newChatterFile);
    return fi; 
}

public static void setAccountingData () {
Map<String, Accounting_Category__c> mcats = new Map<String, Accounting_Category__c> ();
    
    mcats.put('Salary', new Accounting_Category__c(Name = 'Salary', Category_Code__c = 'SALARY', Display_Order__c = 99) );
    mcats.put('Travel', new Accounting_Category__c(Name = 'Travel', Category_Code__c = 'EXPENSE', Display_Order__c = 2) );
    mcats.put('Office', new Accounting_Category__c(Name = 'Office', Category_Code__c = 'EXPENSE', Display_Order__c = 3) );
    mcats.put('Rent', new Accounting_Category__c(Name = 'Rent', Category_Code__c = 'EXPENSE', Display_Order__c = 4) );
    mcats.put('Consulting', new Accounting_Category__c(Name = 'Consulting', Category_Code__c = 'EXPENSE', Display_Order__c = 4) );

    mcats.put('Revenue', new Accounting_Category__c(Name = 'Revenue', Category_Code__c = 'REVENUE', Display_Order__c = 99) );
    
    mcats.put('OPERATIONAL OVERHEAD', new Accounting_Category__c(Name = 'OPERATIONAL OVERHEAD', Category_Code__c = 'OVERHEAD', Display_Order__c = 4) );
    mcats.put('Fringe Benefits', new Accounting_Category__c(Name = 'Fringe Benefits', Category_Code__c = 'FRINGE BENEFIT', Display_Order__c = 99) );
    mcats.put('Applied Grant Overhead', new Accounting_Category__c(Name = 'Applied Grant Overhead', Category_Code__c = 'OVERHEAD', Display_Order__c = 99) );
    insert mcats.values();

    List<Accounting_Code__c> acodes = new List<Accounting_Code__c> ();
    acodes.add (new Accounting_Code__c (Name = '7000',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Salary').Id) );
    acodes.add (new Accounting_Code__c (Name = '7100',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Fringe Benefits').Id) );
    acodes.add (new Accounting_Code__c (Name = '7200',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Consulting').Id) );
    

    acodes.add (new Accounting_Code__c (Name = '7315',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    acodes.add (new Accounting_Code__c (Name = '7450',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    acodes.add (new Accounting_Code__c (Name = '7400',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    acodes.add (new Accounting_Code__c (Name = '7520',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    acodes.add (new Accounting_Code__c (Name = '7540',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    
    acodes.add (new Accounting_Code__c (Name = '7700',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Travel').Id) );
    acodes.add (new Accounting_Code__c (Name = '7720',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Rent').Id) );
    acodes.add (new Accounting_Code__c (Name = '7730',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Rent').Id) );

    acodes.add (new Accounting_Code__c (Name = '7995',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Applied Grant Overhead').Id) );
    acodes.add (new Accounting_Code__c (Name = '7990',Include_on_Budget_Report__c = FALSE,Accounting_Category__c = mcats.get('OPERATIONAL OVERHEAD').Id) );
    
    acodes.add (new Accounting_Code__c (Name = '5200',Include_on_Budget_Report__c = TRUE,Accounting_Category__c = mcats.get('Revenue').Id) );
    
    insert acodes;
}

@isTest
static void SetupCustomSettingsBudgeUpdate() {
SetupCustomSettings scs = new SetupCustomSettings();
scs.updateSettings();
List<GrantManagementSettings__c> gm = GrantManagementSettings__c.getall().values();
system.assert(gm.size() > 0);

//Test Update of Budget Settings
SetupCustomSettings scs2 = new SetupCustomSettings();
system.assertequals('March 31st 2014', scs2.budmap.get('CurrentDataMonth').String_Value__c);
system.assertequals('3200', scs2.budmap.get('StartingBalanceCode').String_Value__c);

Budget_Settings__c bnew = scs2.budmap.get('CurrentDataMonth');
system.assertequals('March 31st 2014', bnew.String_Value__c);
bnew.String_Value__c = 'December 31st 2014';
scs2.updateRecentMonth();

SetupCustomSettings scs3 = new SetupCustomSettings();
system.assertequals('December 31st 2014', scs3.budmap.get('CurrentDataMonth').String_Value__c);
//Check Existing not changed
system.assertequals('3200', scs3.budmap.get('StartingBalanceCode').String_Value__c);

}


}