src/objects/Budget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Determine&apos;s who has access to Budget Data</description>
    <fields>
        <fullName>Id_Value__c</fullName>
        <label>Id Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <inlineHelpText>To store string values for use in Budget Reports</inlineHelpText>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Budget Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>gm_Department_Reference__c</fullName>
        <formula>gm_Department__r.Name</formula>
        <label>Department Reference</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gm_Related_User_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User Record</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Deliverable__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Deliverables</relationshipLabel>
        <relationshipName>Deliverables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Management__c.object
<CustomObject>
    <fields>
        <fullName>Grant_End_Date__c</fullName>
        <inlineHelpText>Official End Date of Grant</inlineHelpText>
        <label>Grant End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_End__c</fullName>
        <inlineHelpText>End date of grant period.</inlineHelpText>
        <label>Grant Period: End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_Start__c</fullName>
        <inlineHelpText>Start date of grant period.</inlineHelpText>
        <label>Grant Period: Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Provisions__c</fullName>
        <inlineHelpText>Any notes about the grant requirements other than reporting.</inlineHelpText>
        <label>Grant Provisions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grant_Start_Date__c</fullName>
        <inlineHelpText>Official Start Date of Grant</inlineHelpText>
        <label>Grant Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Grant Management</relationshipLabel>
        <relationshipName>Grant_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Grant Management</relationshipLabel>
        <relationshipName>Grant_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Management</label>
    <nameField>
        <label>Grant Management Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GrantManagementSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Grant Management App</description>
    <fields>
        <fullName>Boolean_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Id_Value__c</fullName>
        <label>Id Value</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Management Settings</label>
</CustomObject>

src/objects/Issue_Utility_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store Field Map for Issue Intersection Object VF Component</description>
    <fields>
        <fullName>Issue_Intersection_Field__c</fullName>
        <label>Issue Intersection Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String_Value__c</fullName>
        <inlineHelpText>Store generic string parameters</inlineHelpText>
        <label>String Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Issue Utility Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Grant_Period_End__c</fullName>
        <inlineHelpText>End date of grant period.</inlineHelpText>
        <label>Grant Period: End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Period_Start__c</fullName>
        <inlineHelpText>Start date of grant period.</inlineHelpText>
        <label>Grant Period: Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Provisions__c</fullName>
        <inlineHelpText>Any notes about the grant requirements other than reporting.</inlineHelpText>
        <label>Grant Provisions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Opty_Grant_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map fields from Opportunity to Grant on Conversion</description>
    <fields>
        <fullName>Grant_Field__c</fullName>
        <label>Grant Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Order__c</fullName>
        <defaultValue>999</defaultValue>
        <label>Page Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_on_Page__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Section on Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity to Grant Field Map</label>
</CustomObject>

src/objects/Outreach__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Outreach</relationshipLabel>
        <relationshipName>Outreach</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Outreach</relationshipLabel>
        <relationshipName>Outreach</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Outreach</relationshipLabel>
        <relationshipName>Outreach</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Outreach</label>
    <nameField>
        <label>Outreach Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ParticipationControllerSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Store Field setting for Staff Participation Controller so you can add it to any related object</description>
    <fields>
        <fullName>Staff_Participation_Field__c</fullName>
        <inlineHelpText>What is the field on the Staff Participation Object for this object</inlineHelpText>
        <label>Staff Participation Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Participation Controller Settings</label>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <description>Put the Contact Id of this user&apos;s staff Contact record into this field.</description>
        <inlineHelpText>Put the Contact Id of this user&apos;s staff Contact record into this field.</inlineHelpText>
        <label>Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/SetupCustomSettings.cls
/*
    Copyright (c) 2013, Bridge Farm Consulting Inc
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Bridge Farm Consulting Inc nor 
      Center for American Progress nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Center for American Progress/Bridge Farm Consulting Inc
* @date 2014 (1.x)
* @description 
* This is an unmanaged package, so no install scripts, but this powers a page where user 
* can quickly insert default vales into required custom settings 
*/

public with sharing class SetupCustomSettings {

public List<ParticipationControllerSettings__c> pcesettings  {get;set;}
public List<GrantManagementSettings__c> gm  {get;set;}
public List<Opty_Grant_Fields__c> ogf  {get;set;}
public List<Issue_Utility_Settings__c> issuesettings   {get;set;}
public List<Budget_Settings__c> bud  {get;set;}
public Map<String, Budget_Settings__c> budmap  {get;set;}
Id PermissionSetId;

public SetupCustomSettings() {
SetupSettings();
}

public void SetupSettings () {

    pcesettings = ParticipationControllerSettings__c.getall().values();
    gm = GrantManagementSettings__c.getall().values();
    ogf = Opty_Grant_Fields__c.getall().values();
    bud = Budget_Settings__c.getall().values();
    budmap = Budget_Settings__c.getall(); 
    issuesettings = Issue_Utility_Settings__c.getall().values();
   
    
if (pcesettings.isEmpty()) {
    pcesettings = new List<ParticipationControllerSettings__c> ();  
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Account', Staff_Participation_Field__c = 'Account__c'));
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Opportunity', Staff_Participation_Field__c = 'Opportunity__c'));
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Grant_Management__c', Staff_Participation_Field__c = 'Grant_Management__c'));
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Deliverable__c', Staff_Participation_Field__c = 'Deliverables__c'));
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Outreach__c', Staff_Participation_Field__c = 'Outreach__c'));
    pcesettings.add(new ParticipationControllerSettings__c (Name = 'Project__c', Staff_Participation_Field__c = 'Project__c'));
    
    
    }

if (gm.isEmpty()) {
    gm = new List<GrantManagementSettings__c>();
    gm.add(new GrantManagementSettings__c(Name = 'OurAccountId', Id_Value__c = 'ENTER ID HERE'));
    gm.add(new GrantManagementSettings__c(Name = 'ContactDepartment', String_Value__c = 'gm_Department_Reference__c'));
    gm.add(new GrantManagementSettings__c(Name = 'ContactIdFieldonUser', String_Value__c = 'Contact_ID__c'));
    gm.add(new GrantManagementSettings__c(Name = 'UserFieldonContact', String_Value__c = 'gm_Related_User_Record__c'));
    gm.add(new GrantManagementSettings__c(Name = 'PostLeadStaffertoChatter', Boolean_Value__c = TRUE));
    }

if (ogf.isEmpty()) {
    ogf = new List<Opty_Grant_Fields__c>();
    ogf.add (new Opty_Grant_Fields__c(Name = 'Id', Grant_Field__c = 'Source_Opportunity__c', Page_Order__c = 1, Section_on_Page__c = 1));
    ogf.add (new Opty_Grant_Fields__c(Name = 'Name', Grant_Field__c = 'Name', Page_Order__c = 1, Section_on_Page__c = 1));
    ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Period_Start__c', Grant_Field__c = 'Grant_Start_Date__c', Page_Order__c = 1, Section_on_Page__c = 1));
    ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Period_End__c', Grant_Field__c = 'Grant_End_Date__c', Page_Order__c = 1, Section_on_Page__c = 1));
    ogf.add (new Opty_Grant_Fields__c(Name = 'Grant_Provisions__c', Grant_Field__c = 'Grant_Provisions__c', Page_Order__c = 20, Section_on_Page__c = 2));
    
}

if (bud.isEmpty()) {
    bud = new List<Budget_Settings__c>();
    bud.add (new Budget_Settings__c(Name = 'PermissionSet', Id_Value__c  = 'Enter Perm Id'));
    bud.add (new Budget_Settings__c(Name = 'CompanyCodes', String_Value__c  = 'C1;C2'));
    bud.add (new Budget_Settings__c(Name = 'StartingBalanceCode', String_Value__c  = '3200'));
    bud.add (new Budget_Settings__c(Name = 'CurrentDataMonth', String_Value__c  = 'March 31st 2014'));
    }

if (issuesettings.isEmpty()) {
    issuesettings = new List<Issue_Utility_Settings__c>();
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Account', Issue_Intersection_Field__c  = 'Account__c'));
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Contact', Issue_Intersection_Field__c  = 'Contact__c'));
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Deliverable__c', Issue_Intersection_Field__c  = 'Deliverable__c'));
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Department__c', Issue_Intersection_Field__c  = 'Department__c'));
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Outreach__c', Issue_Intersection_Field__c  = 'Outreach__c'));
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'Project__c', Issue_Intersection_Field__c  = 'Project__c'));
    
    issuesettings.add (new Issue_Utility_Settings__c(Name = 'TaxonomyStrings', String_Value__c  = 'Issue;'));
    }


}

public pageReference updateSettings() {
try{
upsert pcesettings;
upsert gm;
upsert bud;
upsert ogf;

upsert issuesettings;

}
Catch (Exception Ex) {

}
return null;
}

public pageReference updateRecentMonth () {

upsert budmap.values();
return new PageReference ('/');
}

}