src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>gm_Related_User_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User Record</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Deliverable__c.object
<CustomObject>
    <fields>
        <fullName>Departments__c</fullName>
        <label>Departments</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Art &amp; Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Closed__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Deliverables</relationshipLabel>
        <relationshipName>Deliverables</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deliverable</label>
    <nameField>
        <label>Deliverable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliverables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Taxonomy__c</fullName>
        <label>Taxonomy</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Issue_Intersection__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Issue Intersection</relationshipLabel>
        <relationshipName>Issue_Intersection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_for_Related_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Deliverable Wizard to auto-populate Issues based on items such as User, Department</inlineHelpText>
        <label>Default for Related Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deliverable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliverable</label>
        <referenceTo>Deliverable__c</referenceTo>
        <relationshipLabel>Issues Intersection</relationshipLabel>
        <relationshipName>Issues_Intersection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Issue Intersection</relationshipLabel>
        <relationshipName>Issue_Intersection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Issue Intersection</relationshipLabel>
        <relationshipName>Issue_Intersection</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Issues Intersection</relationshipLabel>
        <relationshipName>Issues_Intersection</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Issue Intersection</label>
    <nameField>
        <displayFormat>ISS_LINK-{000000}</displayFormat>
        <label>Issue Intersection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues Intersection</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Staff_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff Participation</relationshipLabel>
        <relationshipName>Staff_Participation</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deliverables__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deliverables</label>
        <referenceTo>Deliverable__c</referenceTo>
        <relationshipLabel>Staff Participation</relationshipLabel>
        <relationshipName>Staff_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Staffer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this staffer a lead staffer on this record?</inlineHelpText>
        <label>Lead Staffer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Staff Participations</relationshipLabel>
        <relationshipName>Staff_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Staff Participation</label>
    <nameField>
        <displayFormat>SPT-{00000}</displayFormat>
        <label>Staff Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IssuesIntersectionController_TEST.cls
/*
    Copyright (c) 2013, Bridge Farm Consulting Inc
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Bridge Farm Consulting Inc nor 
      Center for American Progress nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Center for American Progress/Bridge Farm Consulting Inc
* @date 2014 (1.x)
* @description 
*/

@isTest
private class IssuesIntersectionController_TEST {
    
    @isTest
    static void MainComponentTest() {
    
    Account ourAccount = TestDataFactory_TEST.setupNewAccount(TRUE, 'Our Account');

    TestDataFactory_TEST.setupPCESettings(TRUE);
    TestDataFactory_TEST.setupOrgSettings(TRUE, ourAccount.Id);
   
    Project__c testProject = TestDataFactory_TEST.setupNewProject(TRUE, 'Project 1');

    Account testA = TestDataFactory_TEST.setupNewAccount(TRUE, 'Foundation A');
  
    Contact c = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact1', gm_Related_User_Record__c = userinfo.getuserid());
    insert c;

    Contact c2 = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact2', gm_Related_User_Record__c = userinfo.getuserid());
    insert c2;
  
    TestDataFactory_TEST.setupIssueUtilitySettings(FALSE);
    List<issue__c> testIssues = TestDataFactory_TEST.setupIssues();

    Deliverable__c testDeliver = TestDataFactory_TEST.setupNewDeliverable(FALSE, 'Test Deliver 1', testProject.Id);
    testDeliver.Departments__c = 'Child 1;Child 2';
    testDeliver.Project__c = testProject.Id;
    insert testDeliver;

    List<Department__c> testDepts = TestDataFactory_TEST.setupDepartments();

    //Create Defaults
    List<Issue_Intersection__c> iisdefaults = new List<Issue_Intersection__c> ();
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[0].Id, Department__c = testDepts[0].Id, Default_for_Related_Item__c = TRUE)); //Child 1 - Child 1
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[0].Id, Department__c = testDepts[2].Id, Default_for_Related_Item__c = TRUE)); //Child 1 - Child 2
    
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[0].Id, Project__c = testProject.Id, Default_for_Related_Item__c = TRUE)); //Child 1 - Child 2
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[1].Id, Department__c = testDepts[2].Id, Default_for_Related_Item__c = TRUE)); //Child 1a - Child 2

    insert iisdefaults;
 
    PageReference pageRef = Page.NewDeliverableIssues;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('Id', testDeliver.Id);
    

    IssuesIntersectionController bfc = new  IssuesIntersectionController();
    
    bfc.objectId = testDeliver.Id;
    bfc.sMode = 'NEWWITHDEFAULT';
    bfc.sSource = 'Page';

    //Initiates List Population Process
    bfc.getTaxonomySections();

    List<IssuesIntersectionController.issueselectionwrapper> testiiw = bfc.TaxonomySectionMap.get('Issue');
    system.assertequals(2, testiiw.size());
    Issue__c issue1 = testiiw[0].issue;
    system.assert(issue1.Name.Contains('Child 1'));
    
    bfc.processSelectedIssues();

    //Create Defaults - should create 2 records to show we do not create dupe issue references 
    List<Issue_Intersection__c> testdefaults = [SELECT Id FROM Issue_Intersection__c WHERE Deliverable__c = :testDeliver.Id];
    system.assertequals(2, testdefaults.size());    

    //Now invoke again in update mode
    PageReference pageRef2 = Page.NewDeliverableIssues;
    Test.setCurrentPage(pageRef2);
    ApexPages.currentPage().getParameters().put('Id', testDeliver.Id);
    
    IssuesIntersectionController bfc2 = new  IssuesIntersectionController();
    
    bfc2.objectId = testDeliver.Id;
    bfc2.sMode = 'UPDATE';
    bfc2.sSource = 'Page';
    bfc2.sNextPage = 'ContactIssue';


    bfc2.getTaxonomySections();

    ApexPages.currentPage().getParameters().put('rcid', testIssues[0].Id);

    bfc2.removeSelectedIssue();
    bfc2.processSelectedIssues();

    //Create Defaults - should create 2 records to show we do not create dupe issue references 
    testdefaults = [SELECT Id, Issue__c FROM Issue_Intersection__c WHERE Deliverable__c = :testDeliver.Id];
    system.assertequals(1, testdefaults.size());    
    system.assertequals(testIssues[1].Id, testdefaults[0].Issue__c);    

    //Check Cancel
    String sCancel = bfc2.cancelupdate().geturl();
    system.assertequals ('/'+testDeliver.Id, sCancel);


    }

@isTest
    static void MainComponentTestStaffDefaults() {
    
    Account ourAccount = TestDataFactory_TEST.setupNewAccount(TRUE, 'Our Account');

    TestDataFactory_TEST.setupPCESettings(TRUE);
    TestDataFactory_TEST.setupOrgSettings(TRUE, ourAccount.Id);
   
    Account testA = TestDataFactory_TEST.setupNewAccount(TRUE, 'Foundation A');
  
    Contact c = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact1', gm_Related_User_Record__c = userinfo.getuserid());
    insert c;

    Contact c2 = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact2', gm_Related_User_Record__c = userinfo.getuserid());
    insert c2;
  
    TestDataFactory_TEST.setupIssueUtilitySettings(FALSE);
    List<issue__c> testIssues = TestDataFactory_TEST.setupIssues();

    Project__c testProject = TestDataFactory_TEST.setupNewProject(TRUE, 'Project 1');


    Deliverable__c testDeliver = TestDataFactory_TEST.setupNewDeliverable(FALSE, 'Test Deliver 1', testProject.Id);
    testDeliver.Departments__c = 'Child 1;Child 2';
    insert testDeliver;

    List<Department__c> testDepts = TestDataFactory_TEST.setupDepartments();

    //Create Staff Defaults
    List<Staff_Participation__c> spList = new List<Staff_Participation__c> ();
    spList.add(new Staff_Participation__c(Contact__c = c.Id, Deliverables__c = testDeliver.Id, Lead_Staffer__c = TRUE));
    spList.add(new Staff_Participation__c(Contact__c = c2.Id, Deliverables__c = testDeliver.Id, Lead_Staffer__c = FALSE));
    insert spList;

    List<Issue_Intersection__c> iisdefaults = new List<Issue_Intersection__c> ();
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[0].Id, Contact__c = c.Id, Default_for_Related_Item__c = TRUE)); //Child 1 - Child 1
    iisdefaults.add(new Issue_Intersection__c(Issue__c = testIssues[1].Id, Contact__c = c2.Id, Default_for_Related_Item__c = TRUE)); //Child 1a - Child 2

    insert iisdefaults;
 
    PageReference pageRef = Page.NewDeliverableIssues;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('Id', testDeliver.Id);
    

    IssuesIntersectionController bfc = new  IssuesIntersectionController();
    
    bfc.objectId = testDeliver.Id;
    bfc.sMode = 'NEWWITHDEFAULT';
    bfc.sSource = 'Page';

    //Initiates List Population Process
    bfc.getTaxonomySections();

    List<IssuesIntersectionController.issueselectionwrapper> testiiw = bfc.TaxonomySectionMap.get('Issue');
    system.assertequals(2, testiiw.size());
    Issue__c issue1 = testiiw[0].issue;
    system.assert(issue1.Name.Contains('Child 1'));
    Issue_Intersection__c iss1 = testiiw[0].issueintersection;
    system.assertEquals('Contact', iss1.Object__c);
    system.assertEquals(testDeliver.Id, iss1.Deliverable__c);

    bfc.processSelectedIssues();

    //Create Defaults - should create 2 records to show we do not create dupe issue references 
    List<Issue_Intersection__c> testdefaults = [SELECT Id FROM Issue_Intersection__c WHERE Deliverable__c = :testDeliver.Id];
    system.assertequals(2, testdefaults.size());    

    
    }


    @isTest
    static void MainComponentTestNoDefaults() {
    
    Account ourAccount = TestDataFactory_TEST.setupNewAccount(TRUE, 'Our Account');

    TestDataFactory_TEST.setupPCESettings(TRUE);
    TestDataFactory_TEST.setupOrgSettings(TRUE, ourAccount.Id);
   
    Account testA = TestDataFactory_TEST.setupNewAccount(TRUE, 'Foundation A');
  
    Contact c = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact1', gm_Related_User_Record__c = userinfo.getuserid());
    insert c;

    Contact c2 = new Contact (AccountId = ouraccount.Id, LastName = 'Test Contact2', gm_Related_User_Record__c = userinfo.getuserid());
    insert c2;
  
    TestDataFactory_TEST.setupIssueUtilitySettings(FALSE);
    List<issue__c> testIssues = TestDataFactory_TEST.setupIssues();


    Project__c testProject = TestDataFactory_TEST.setupNewProject(TRUE, 'Project 1');

    Deliverable__c testDeliver = TestDataFactory_TEST.setupNewDeliverable(FALSE, 'Test Deliver 1', testProject.Id);
    testDeliver.Departments__c = 'Child 1;Child 2';
    insert testDeliver;

    List<Department__c> testDepts = TestDataFactory_TEST.setupDepartments();

    PageReference pageRef = Page.NewDeliverableIssues;
    Test.setCurrentPage(pageRef);
    ApexPages.currentPage().getParameters().put('Id', testDeliver.Id);
    
    IssuesIntersectionController bfc = new  IssuesIntersectionController();
    
    bfc.objectId = testDeliver.Id;
    bfc.sMode = 'NEWWITHDEFAULT';
    bfc.sSource = 'Page';

    //Initiates List Population Process
    bfc.getTaxonomySections();

    List<IssuesIntersectionController.issueselectionwrapper> testiiw = bfc.TaxonomySectionMap.get('Issue');
    system.assertequals(0, testiiw.size());
    bfc.cIssueId = testIssues[0].Parent_Issue__c;

    bfc.search();

    system.assertequals(2, bfc.newIssuesforSelection.size());
    system.assertequals('Child 1a', bfc.newIssuesforSelection[0].Name);
    system.assertequals('Issue', bfc.newIssuesforSelection[0].Taxonomy__c);
    
    ApexPages.currentPage().getParameters().put('cid', testIssues[0].Id);

    bfc.setSelectedIssue();
    bfc.processAction();

    //Check when update via Chatter Publisher Action
    system.assertequals(TRUE, bfc.bPosted);

    //Check Records Created
    List<Issue_Intersection__c> testdefaults = [SELECT Id FROM Issue_Intersection__c WHERE Deliverable__c = :testDeliver.Id];
    system.assertequals(1, testdefaults.size());    


}
    
        
}